# Generated by Django 5.2.4 on 2026-09-10 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='نشانی'),
        ),
        migrations.AddField(
            model_name='business',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='دامنه\u200cی اختصاصی'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='business',
            name='subdomain',
            field=models.SlugField(blank=True, help_text='نشانی سایت شما: نام\u200cشما.servisa.ir', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ساب\u200cدامین فقط حروف انگلیسی کوچک، عدد و خط تیره (۳ تا ۳۲ نویسه).', regex='^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$')], verbose_name='ساب\u200cدامین'),
        ),
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=160, verbose_name='شعار / توضیح کوتاه'),
        ),
    ]
