# Generated by Django 6.1.1 on 2026-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_backfill_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='برای دیده\u200cشدن در جست\u200cوجوی محلی گوگل، مثلاً: کرمان', max_length=60, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، در صفحه\u200cی شهر نمایش داده نمی\u200cشود.', verbose_name='نمایش در فهرست عمومی سرویسا'),
        ),
    ]
