# Generated by Django 5.2.4 on 2026-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_city_business_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
