# Generated by Django 6.1 on 2026-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کدهای تایید',
                'ordering': ['-created_at'],
            },
        ),
    ]
