# Generated by Django 6.1.1 on 2026-09-09 08:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ تعویض')),
                ('mileage_km', models.PositiveIntegerField(verbose_name='کیلومتر (کارکرد)')),
                ('oil_name', models.CharField(blank=True, help_text='اختیاری، مثلاً: بهران توربین ۲۰W۵۰', max_length=100, verbose_name='نوع روغن')),
                ('interval_km', models.PositiveIntegerField(default=5000, verbose_name='فاصله تا تعویض بعدی (کیلومتر)')),
                ('interval_months', models.PositiveIntegerField(default=3, verbose_name='فاصله تا تعویض بعدی (ماه)')),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='کیلومتر موعد بعدی')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ موعد بعدی')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_changes', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to='vehicles.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'تعویض روغن',
                'verbose_name_plural': 'تعویض روغن\u200cها',
                'ordering': ['-service_date', '-id'],
            },
        ),
    ]
