# Generated by Django 6.1.1 on 2026-09-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('oilchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchange',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='catalog.product', verbose_name='محصول'),
        ),
    ]
