# Generated by Django 6.1 on 2026-09-22 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, help_text='فارسی و یکتا؛ در نشانی صفحه می\u200cآید، مثلاً: روغن-موتور', max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.CharField(blank=True, help_text='در صفحه\u200cی دسته و متای سئو استفاده می\u200cشود.', max_length=300, verbose_name='توضیح کوتاه')),
                ('icon_svg', models.TextField(blank=True, help_text='محتوای داخل تگ svg، مثلاً <path .../> — هماهنگ با آیکون\u200cهای محصول.', verbose_name='آیکون (مسیر SVG)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='نام برچسب')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, help_text='فارسی و یکتا؛ کلمه\u200cی کلیدی داخل نشانی، مثلاً: هر-چند-وقت-روغن-موتور', max_length=160, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.CharField(help_text='در کارت\u200cها، متای description و نتایج گوگل نمایش داده می\u200cشود.', max_length=300, verbose_name='چکیده')),
                ('content', models.TextField(help_text='از h2 و h3 برای سرتیتر استفاده کن تا فهرست خودکار ساخته شود.', verbose_name='متن مقاله (HTML)')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='لیستی از {"q": "پرسش", "a": "پاسخ"}', verbose_name='پرسش\u200cهای متداول')),
                ('meta_title', models.CharField(blank=True, max_length=170, verbose_name='عنوان سئو (meta title)')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح سئو (meta description)')),
                ('og_image', models.URLField(blank=True, help_text='خالی = لوگوی چرخیار.', verbose_name='تصویر اشتراک\u200cگذاری (og:image)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='پیش\u200cنویس\u200cها منتشر نمی\u200cشوند؛ زمان آینده = انتشار زمان\u200cبندی\u200cشده.', null=True, verbose_name='زمان انتشار')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه (در صدر وبلاگ)')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='زمان مطالعه (دقیقه)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
        ),
    ]
