# Generated by Django 5.2.4 on 2026-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_seed_kerman_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='افقی و با کیفیت (حداقل ۱۲۰۰×۶۷۵). خالی = آیکون دسته.', upload_to='blog/covers/', verbose_name='عکس کاور'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='توصیف کوتاه عکس برای گوگل و نابینایان. خالی = عنوان مقاله.', max_length=200, verbose_name='متن جایگزین عکس (alt)'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_static',
            field=models.CharField(blank=True, help_text='مثلاً img/blog/oil-refill.webp — فقط وقتی «عکس کاور» خالی است.', max_length=200, verbose_name='عکس کاور (مسیر static)'),
        ),
    ]
