# Generated by Django 6.1.1 on 2026-09-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: پژو ۲۰۶ سفید', max_length=100, verbose_name='خودرو')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تعویض')),
                ('last_mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='کارکرد در آخرین تعویض')),
                ('last_oil_name', models.CharField(blank=True, max_length=100, verbose_name='روغن آخر')),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='موعد بعدی')),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='کیلومتر موعد بعدی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
