# Generated by Django 5.2.4 on 2026-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avg_daily_km',
            field=models.FloatField(blank=True, null=True, verbose_name='میانگین کیلومتر روزانه'),
        ),
    ]
