# Generated by Django 5.2.4 on 2026-09-10 12:26

from django.db import migrations


def backfill(apps, schema_editor):
    """نرخ روزانه را برای خودروهای موجود از روی تاریخچه تخمین بزن."""
    from core import mileage

    Vehicle = apps.get_model("vehicles", "Vehicle")
    for vehicle in Vehicle.objects.all():
        changes = list(vehicle.oil_changes.all())
        rate = mileage.average_daily_km(changes)
        if rate != vehicle.avg_daily_km:
            vehicle.avg_daily_km = rate
            vehicle.save(update_fields=["avg_daily_km"])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_avg_daily_km'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
