# Generated by Django 6.1.1 on 2026-09-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_backfill_subdomains'),
        ('vehicles', '0003_backfill_avg_daily_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='برند')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_brands', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'برند خودرو',
                'verbose_name_plural': 'برندهای خودرو',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='مدل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'مدل خودرو',
                'verbose_name_plural': 'مدل\u200cهای خودرو',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('color', 'رنگ'), ('oil', 'نوع روغن'), ('fuel', 'نوع سوخت')], db_index=True, max_length=10, verbose_name='نوع گزینه')),
                ('name', models.CharField(max_length=80, verbose_name='عنوان')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_options', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'گزینه\u200cی خودرو',
                'verbose_name_plural': 'گزینه\u200cهای خودرو',
                'ordering': ['kind', 'sort_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclebrand',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_brand_per_business'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_model_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='vehicleoption',
            constraint=models.UniqueConstraint(fields=('business', 'kind', 'name'), name='unique_option_per_business_kind'),
        ),
    ]
