# Generated by Django 6.1.1 on 2026-09-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_seed_vehicle_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vehiclebrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'color'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_with_color', to='vehicles.vehicleoption', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'fuel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_with_fuel', to='vehicles.vehicleoption', verbose_name='نوع سوخت'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vehiclemodel', verbose_name='مدل'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='title',
            field=models.CharField(blank=True, help_text='مثلاً: پژو ۲۰۶ سفید', max_length=100, verbose_name='خودرو'),
        ),
    ]
