# Generated by Django 6.1.1 on 2026-09-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_brand_vehicle_color_vehicle_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='preferred_oil',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'oil'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_with_oil', to='vehicles.vehicleoption', verbose_name='روغن پیشنهادی'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_km',
            field=models.PositiveIntegerField(blank=True, help_text='اگر خالی بماند، از آخرین تعویض یا پیش\u200cفرض استفاده می\u200cشود.', null=True, verbose_name='فاصله سرویس (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فاصله سرویس (ماه)'),
        ),
    ]
