# Generated by Django 6.1 on 2026-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_preferred_oil_vehicle_service_interval_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_mileage_km',
            field=models.PositiveIntegerField(default=0, help_text='کارکرد فعلی خودرو بر اساس کیلومترشمار.', verbose_name='کیلومتر فعلی'),
        ),
    ]
