"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# متغیرهای محیطی را از فایل .env (در صورت وجود) می‌خوانیم.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# در تولید حتماً DJANGO_SECRET_KEY را در محیط تنظیم کنید.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-*saf9^v0x7*s@&5j$izg3zs+c4_n1zi-x$hzc0ugmq)_w15dq4",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "on")

# --- میزبان‌ها و چند-مستأجری (multitenancy) ---
# دامنه‌ی پایه‌ی سرویسا؛ ساب‌دامین هر نماینده: <subdomain>.<TENANT_BASE_DOMAIN>
TENANT_BASE_DOMAIN = "servisa.ir"

# در توسعه، ساب‌دامین‌های *.localhost روی 127.0.0.1 حل می‌شوند؛
# پس لینک‌های ساخته‌شده در حالت DEBUG از این دامنه استفاده می‌کنند.
TENANT_DEV_BASE_DOMAIN = "localhost"

# میزبان‌های خودِ پلتفرم (لندینگ عمومی سرویسا، پنل مالک پلتفرم و ...)
# روی این میزبان‌ها request.business = None و urlconf پیش‌فرض استفاده می‌شود.
PLATFORM_HOSTS = ["localhost", "127.0.0.1", "servisa.ir", "www.servisa.ir"]

# پورت توسعه برای ساخت لینک ساب‌دامین‌ها (فقط وقتی DEBUG)
TENANT_DEV_PORT = "8000"

# ===================== سئو (SEO) =====================
# نشانی متعارف (canonical) سایت. همه‌ی لینک‌های مطلقِ سئو — canonical،
# sitemap.xml، Open Graph و JSON-LD — از همین یک مقدار ساخته می‌شوند؛
# پس برای تغییر دامنه فقط همین خط عوض می‌شود.
SITE_SCHEME = "https"
SITE_DOMAIN = TENANT_BASE_DOMAIN          # servisa.ir
SITE_URL = f"{SITE_SCHEME}://{SITE_DOMAIN}"
SITE_NAME = "سرویسا"

# شهرِ تمرکزِ سئوی محلی. صفحه‌ی «تعویض روغنی در <شهر>» برای این شهرها
# ساخته و در sitemap ثبت می‌شود.
SEO_PRIMARY_CITY = "کرمان"
SEO_CITIES = ["کرمان"]

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".localhost",       # هر ساب‌دامین *.localhost در توسعه
    ".servisa.ir",      # هر ساب‌دامین *.servisa.ir در تولید
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://*.localhost:8000",
    "https://servisa.ir",
    "https://*.servisa.ir",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    "core",

    "apps.accounts",
    "apps.blog",
    "apps.businesses",
    "apps.catalog",
    "apps.customers",
    "apps.vehicles",
    "apps.oilchange",
    "apps.orders",
    "apps.pages",
    "apps.tenants",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.nav_badges',
                'core.seo.seo_defaults',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email (در توسعه: چاپ در کنسول)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# احراز هویت
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "businesses:dashboard"
LOGOUT_REDIRECT_URL = "home"


# آدرس پایه‌ی سایت برای ساخت لینک‌های مطلق خارج از request (مثلاً در پیامک)
SITE_BASE_URL = "http://localhost:8000"