# Generated by Django 6.1.1 on 2026-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه (slug)')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='توضیح یک\u200cخطی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon_svg', models.TextField(blank=True, help_text='محتوای داخل تگ svg، مثلاً <path .../>', verbose_name='آیکون (مسیر SVG)')),
                ('is_available', models.BooleanField(default=False, help_text='اگر خاموش باشد، محصول به\u200cصورت «به\u200cزودی» نمایش داده می\u200cشود.', verbose_name='فعال است')),
                ('is_flagship', models.BooleanField(default=False, verbose_name='محصول پرچم\u200cدار')),
                ('tracks_mileage', models.BooleanField(default=True, verbose_name='بر اساس کارکرد (کیلومتر)')),
                ('default_interval_km', models.PositiveIntegerField(default=5000, verbose_name='فاصله پیش\u200cفرض (کیلومتر)')),
                ('default_interval_months', models.PositiveIntegerField(default=3, verbose_name='فاصله پیش\u200cفرض (ماه)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
