# Generated by Django 6.1.1 on 2026-09-14 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_backfill_subdomains'),
        ('catalog', '0002_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, help_text='خالی = محصول سراسری پلتفرم.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='شناسه (slug)'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='unique_product_slug_per_business'),
        ),
    ]
